### ISSUE TITLE
Too many redirects on Cloud Wifi network

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/grantnav#357] opened 2016-11-17 14:58 UTC
We're seeing a weird issue when accessing from the DFID public wifi network (provided by the cloud).

A simple search results in:

![image](https://cloud.githubusercontent.com/assets/342624/20393943/b7d51c3c-acd5-11e6-8a10-b763044758cf.png)

But connecting from the same machine to 3G and running the same search gives results as expected - both with and without cookies set. 

Ah - and from just testing again - this appears to be an intermittent bug (reproduces 

However. Looking at the network report from Chrome Inspector, I do see a lot of directs each giving a little bit of JSON:

![screen shot 2016-11-17 at 14 56 10](https://cloud.githubusercontent.com/assets/342624/20394035/1590f968-acd6-11e6-9a9f-285baa845f9a.png)

Any ideas? Just a configuration issue here? Or interacting with GrantNav in an odd way we should try and track-down and bug-fix?

**Comment by stevieflow** [comment] 2017-06-01 09:35
I'm on a Cloud network (Wetherspoons!) at the moment, and experience the same issue

**Comment by stevieflow** [comment] 2017-10-12 17:41
I have experienced the same issue today (whilst trying to show someone GN).  We need to look into it, and see what fix can be applied

**Comment by robredpath** [comment] 2017-10-24 09:53
@stevieflow do you have your DNS resolver set to anything other than 'use what I get given via DHCP', otherwise known as 'automatic'? That seems to be suggested as a cause in https://discussions.apple.com/thread/6289548?tstart=0

**Comment by stevieflow** [comment] 2017-10-24 09:58
I dont think so... I know this was experienced by @timgdavies too...

**Comment by Bjwebb** [comment] 2018-01-11 14:46
I'm currently connected to "_The Cloud" wifi, and unable to reproduce this issue.

@timgdavies  Looks like part of your original issue is missing.

> Ah - and from just testing again - this appears to be an intermittent bug (reproduces

Do you remember how frequently this was reproducing?

**Comment by timgdavies** [comment] 2018-01-11 14:49
I'm afraid this was a long-time ago now.

**Comment by Bjwebb** [comment] 2018-01-11 14:55
Yep, fair enough.

@stevieflow You've seen this more recently. Do you remember if it was happening for every search you tried?

**Comment by Bjwebb** [comment] 2018-01-11 15:07
So, don't know if this matters but my wifi seems to be branded as "Sky WiFi":
![image](https://user-images.githubusercontent.com/634/34832164-ff3e44d0-f6e0-11e7-848e-26c2d104bc60.png)

Although, http://thecloud.net redirect to https://www.skywifi.cloud/ now, so I think this is a change across the board.

**Comment by stevieflow** [comment] 2018-01-11 15:08
I *think* I've only seen it in government departments that have that Cloud wifi - I dont know how to replicate immediately

**Comment by Bjwebb** [comment] 2018-01-11 15:10
@stevieflow I thought you'd seen it in Wetherspoons? https://github.com/OpenDataServices/grantnav/issues/357#issuecomment-305442231

**Comment by stevieflow** [comment] 2018-01-11 15:12
Ah yes!  Erm, I've no _immediate_ plans to go to a spoons... .

**Comment by timgdavies** [comment] 2018-01-11 15:44
I'll put a quick tweet out to ask if anyone can help test by:

* Checking they are connected through Wifi from The Cloud
* Going to http://grantnav.threesixtygiving.org/
* Entering a search
* Reporting back if the page displays some results, or an error about too many redirections

**Comment by Bjwebb** [comment] 2018-01-16 09:31
@edugomez is going to have

**Comment by Bjwebb** [comment] 2018-01-16 09:32
@edugomez is going to test this in Wetherspoons, and if we can't reproduce there, we'll close this issue.

**Comment by edugomez** [comment] 2018-01-19 09:41
From conversation with @timgdavies, this doesn't seem to be a problem ATM, nobody is complaining, so we are closing this issue and see if it comes up again.

**Closed by edugomez** 2018-01-19 09:41 UTC
Labels: bug - not as designed, website operations

**Comment by Bjwebb** [comment] 2018-01-19 16:58
I can confirm this seems to work fine on the Wetherspoon's wifi now also.

**Comment by edugomez** [comment] 2018-01-19 17:00
@Bjwebb have a beer to celebrate then :)

**Comment by morchickit** [comment] 2018-01-19 17:05
Oh Ben you are amazing!

**Comment by timgdavies** [comment] 2018-02-27 15:25
Further Weatherspoons testing confirms this.
