### ISSUE TITLE
Server Error (500) error related to Funder name

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/grantnav#414] opened 2017-12-08 11:15 UTC
I wanted to link to GrantNav with results filtered by funder Joseph Rowntree Foundation.
I couldn't find them in the Funder filters (they only show first 55, I think) so I tried to search for 'Joseph Rowntree Foundation' but got a Server Error (500) error. 
I get this when searching for Joseph Rowntree too, but not just Joseph. I tried other search terms 'mental health' 'domestic violence' are not affected. Joseph Rowntree Charitable Trust as a search term is not affected either!
When I did a search for York, I was able to filter by JRF. However I got the server error again if I run search without search terms with JRF filtered.

**Comment by Bjwebb** [comment] 2017-12-08 11:24
Looks like this is due to this issue: https://github.com/OpenDataServices/grantnav/issues/386

**Comment by KDuerden** [comment] 2017-12-08 11:53
So can be fixed via an update to the data - eg there is a stray character in there making it break?

**Comment by Bjwebb** [comment] 2017-12-08 11:59
Yes the problem is a newline in a recipient id `GB-CHC-\n1120420` (in the file "JRF York Committee’s small grants awarded in 2017"), so that can be fixed in the data.

**Comment by Bjwebb** [comment] 2017-12-08 11:59
I think there's a few other similar problems in that file also.

**Comment by KDuerden** [comment] 2017-12-08 12:04
I had seen those (eg few broken org Id links) so was planning to feedback. Hadn't realised there would be this knock-on effect. Thanks!

**Comment by Bjwebb** [comment] 2017-12-08 12:23
Looks like I can also fix the problem in GrantNav by allowing newlines in urls. The data still needs updating, as the identifier with/without the newline become different pages; but updating GrantNav would mean the failure isn't so broad (ie. breaking an entire search results page, when only a few results are wrong).

**Comment by morchickit** [comment] 2018-11-05 13:10
Can we close this issues? Or this still happens?

**Closed** 2018-11-06 12:59 UTC
