### ISSUE TITLE
Grant duration field is always empty when downloading the data from 

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#435] opened 2018-01-16 14:16 UTC
An example - when Looking at Somerset Community Foundation XLS, there is a field name Planned Dates:Duration (months), however, when looking at Planned Dates:Duration (months) in GrantNav when downloading a CSV with the search , that field (Planned Dates:Duration (months)) is empty.

**Comment by morchickit** [comment] 2018-01-19 15:30
@robredpath - just heads up since I think it's a bug.

**Comment by Bjwebb** [comment] 2018-01-19 17:37
I can confirm that this a bug, due to a typo basically, so easy to fix.

**Comment by morchickit** [comment] 2018-01-19 18:12
Good to know. I was afraid this is more complicated to fix! Gen will be happy to know it is fixed now! :-)

**Comment by Bjwebb** [comment] 2018-01-22 09:57
This is now fixed on the dev site:
http://current.acceptable-license-valid.master.grantnav-dev.default.threesixtygiving.uk0.bigv.io/

**Closed by Bjwebb** 2018-01-22 09:57 UTC
Labels: bug - not as designed
