### ISSUE TITLE
Data Sources list

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#60] opened 2016-04-07 10:26 UTC
I'd like to see a page that lists the data sources used in the application, along with licence information.

This should help us start to answer the question about which data has been loaded into the application.

**Comment by caprenter** [comment] 2016-04-07 12:02
I'm gonna add:
Date retrieved (and loaded maybe?) to this list

**Comment by stevieflow** [comment] 2016-04-07 13:10
This is useful / interesting

I'd like to know if the data source info would differ from the public registry (or be a duplicate of).

> Date retrieved (and loaded maybe?)

Also useful.  Does this lead to the availability of all the source data under the instance of GrantNav being made available ?

**Comment by caprenter** [comment] 2016-04-07 14:24
What is "the public registry"?

GrantNav (or an instance of GrantNav) only contains the data that we choose to put into it. 
That could be 'current data', historic data, part of the current data available etc etc

So while I'm not sure what the 'public registry' is I can easily see how it could differ.

As to:
"Does this lead to the availability of all the source data under the instance of GrantNav being made available ?"
The point is to tell people what data is in the application, where it came from and when it was retrieved, and how it was licensed at the time.
For people to re-use from data directly from GrantNav it would need to be re-licensed
If you list a URL from which you grabbed some data yesterday, people could try that URL - but they could not try it yesterday.

**Comment by robredpath** [comment] 2016-06-21 16:42
Closing in favour of #137 , although copying some notes over there

**Closed by robredpath** 2016-06-21 16:42 UTC
